name: Linux build

on: [push]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64
      - name: prepare
        run: |
          sudo apt-get update
          sudo apt-get install xorg libasound2 libgtk2.0-0
      - name: compile
        run: |
          ./gradlew assemble example:assemble
          ./gradlew test